export interface IPayByPrimeParams {
  /**
   * The one time token returned from getPrime.
   * You can use this prime for test in sandbox environment.
   * prime : test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9
   */
  prime: string;
  /**
   * Involved merchant’s identifier as defined on Portal.
   */
  merchant_id: string;
  /**
   * Transaction price.
   */
  amount: number;
  /**
   * The letter abbreviation for currency, following ISO 4217.
   */
  currency?: string;
  /**
   * A self-defined identifier for each transaction, for TapPay to identify transaction.
   */
  order_number?: string;
  /**
   * Transaction identifier for the bank.
   * You may customize one here if you wish, but it must be unique.
   */
  bank_transaction_id?: string;
  /**
   * Details of the transaction.
   * You should include as much information as possible.
   * It will help our fraud detector in distinguishing real and fake transaction.
   */
  details: string;
  /**
   * Information of the cardholder
   * Optional parameters should have the matching key as well,
   * with empty string as the value. e.g. zip_code: “”, address: “”, national_id: “”
   */
  cardholder: {
    phone_number: string;
    name: string;
    email: string;
    zip_code: string;
    address: string;
    national_id: string;
  };
  /**
   * Number of intervals of payments for a particular transaction.
   * Default set this value as 0. ( Not available in Apple Pay and Android Pay )
   */
  instalment?: number;
  /**
   * The number of days between the time bank authorizes the payment and the time bank actually captures the payment.
   * Default is 0.
   * If you wish to capture the payment yourself, use -1 as the value to disable automatic capture.
   */
  delay_capture_in_days?: number;
  /**
   * To save the card number or not. Not Available to Apple Pay or Android Pay.
   */
  remember: boolean;
}

export interface IPayByPrimeResponse {
  /**
   * Response code. 0 indicates success.
   */
  status:	number;
  /**
   * Error message.
   */
  msg: string;
  /**
   * Unique identifier for this transaction generated by our server.
   */
  rec_trade_id: string;
  /**
   * Transaction identifier for the bank.
   * You may customize one here if you wish, but it must be unique.
   */
  bank_transaction_id: string;
  /**
   * Bank authorization code.
   */
  auth_code: string;
  /**
   * Contains the card key and token. Only returned if the “remember” parameter in payByPrime API is set to true
   */
  card_secret?: {
    card_key: string;
    card_token: string;
  };
  /**
   * Transaction price.
   */
  amount: number;
  /**
   * Card information.
   */
  card_info: {
    /**
     * First six digits of the card
     */
    bin_code: string;
    /**
     * Last four digits of the card
     */
    last_four: string;
    /**
     * Card issuer
     */
    issuer: string;
    /**
     * Card usage
     * 0 = credit card
     * 1 = debit card
     * 2 = prepaid card
     */
    funding: number;
    /**
     * Card type
     * 1 = VISA
     * 2 = MasterCard
     * 3 = JCB
     * 4 = Union Pay
     * 5 = AMEX
     */
    type: number;
    /**
     * Card level
     */
    level: string;
    /**
     * Country of card issuer
     */
    country: string;
    /**
     * Country code of card issuer
     */
    country_code: string;
    /**
     * Card expired date, Format : YYYYMM,
     */
    expiry_date: string;
  };
  /**
   * A self-defined identifier for each transaction, for TapPay to identify transaction.
   */
  order_number: string;
  /**
   * Acquiring banks or payment processors.
   */
  acquirer: string;
  /**
   * Time of transaction.
   */
  transaction_time_millis: number;
  /**
   * Time when the bank handles the transaction.
   */
  bank_transaction_time: {
    start_time_millis: number;
    end_time_millis: number;
  };
  /**
   * Response code from the bank.
   */
  bank_result_code: string;
  /**
   * Error message from the bank.
   */
  bank_result_msg: string;
}
